(()=>{
'use strict';
const LAT=14.230586,LON=47.199415;
window.MODEL_LIST=[['ECMWF','ecmwf_ifs025'],['GFS','gfs_seamless'],['ICON','icon_seamless'],['GEM / CMC','gem_seamless'],['AIFS','ecmwf_aifs025']];
window.haversine=function(a,b,c,d){const R=6371,r=x=>x*Math.PI/180,da=r(c-a),dl=r(d-b),q=Math.sin(da/2)**2+Math.cos(r(a))*Math.cos(r(c))*Math.sin(dl/2)**2;return 2*R*Math.asin(Math.sqrt(q));};
const oldModels=window.openModels,oldQuakes=window.openQuakes,oldSea=window.openSea;
window.openModels=function(){oldModels?.();window.modelsLoaded=false;if(typeof window.loadModels==='function')window.loadModels();};
window.openQuakes=function(){oldQuakes?.();window.quakesLoaded=false;if(typeof window.loadQuakes==='function')window.loadQuakes();};
const seaPoints=[['غرب بحر العرب',12,52],['شرق سقطرى',12,55],['شمال غرب بحر العرب',16,55],['وسط بحر العرب الغربي',14,58],['شمال بحر العرب',18,58],['وسط بحر العرب',14,61],['شمال بحر العرب',18,61],['وسط بحر العرب الشرقي',14,64],['شمال شرق بحر العرب',18,64],['شرق بحر العرب',14,67],['جنوب بحر العرب',10,58],['جنوب شرق بحر العرب',10,64]];
function set(id,v){const e=document.getElementById(id);if(e)e.textContent=v;}
function dir(deg){const x=['شمالية','شمالية شرقية','شرقية','جنوبية شرقية','جنوبية','جنوبية غربية','غربية','شمالية غربية'];return x[Math.round(Number(deg||0)/45)%8];}
async function seaPoint(p){const u=`https://api.open-meteo.com/v1/forecast?latitude=${p[1]}&longitude=${p[2]}&hourly=pressure_msl,precipitation,cloud_cover,relative_humidity_2m,wind_speed_10m,wind_direction_10m&timezone=Asia%2FAden&forecast_days=3&cell_selection=sea`;const r=await fetch(u);if(!r.ok)throw Error('sea');const d=await r.json(),h=d.hourly||{};let best=0,score=-1,minP=9999,maxR=0,maxC=0,maxH=0,maxW=0;for(let i=0;i<(h.time||[]).length;i++){const P=Number(h.pressure_msl?.[i]),R=Number(h.precipitation?.[i]||0),C=Number(h.cloud_cover?.[i]||0),H=Number(h.relative_humidity_2m?.[i]||0),W=Number(h.wind_speed_10m?.[i]||0),s=Math.max(0,1012-(P||1012))*2+R*6+W*.18+C*.035+H*.02;if(Number.isFinite(P))minP=Math.min(minP,P);maxR=Math.max(maxR,R);maxC=Math.max(maxC,C);maxH=Math.max(maxH,H);maxW=Math.max(maxW,W);if(s>score){score=s;best=i;}}return{name:p[0],lat:p[1],lon:p[2],score,minP,maxR,maxC,maxH,maxW,time:h.time?.[best],wind:Number(h.wind_speed_10m?.[best]||0),direction:Number(h.wind_direction_10m?.[best]||0),rain:Number(h.precipitation?.[best]||0),cloud:Number(h.cloud_cover?.[best]||0),pressure:Number(h.pressure_msl?.[best]||0)};}
window.loadSea=async function(){const s=document.getElementById('seaSummary');if(s)s.textContent='🔄 جاري فحص مؤشرات بحر العرب...';try{const out=[];for(let i=0;i<seaPoints.length;i+=4){out.push(...await Promise.all(seaPoints.slice(i,i+4).map(seaPoint)));}const a=out.reduce((x,y)=>y.score>x.score?y:x),dist=window.haversine(LAT,LON,a.lat,a.lon),minP=Math.min(...out.map(x=>x.minP)),maxR=Math.max(...out.map(x=>x.maxR)),maxC=Math.max(...out.map(x=>x.maxC)),maxH=Math.max(...out.map(x=>x.maxH)),maxW=Math.max(...out.map(x=>x.maxW));set('seaArea',a.name);set('seaTime',a.time?new Date(a.time).toLocaleString('ar-YE',{timeZone:'Asia/Aden',weekday:'long',hour:'numeric',minute:'2-digit',hour12:true}):'--');set('seaCoords',`${a.lat.toFixed(1)}°N ، ${a.lon.toFixed(1)}°E`);set('seaDistance',`نحو ${Math.round(dist)} كم`);set('seaPressure',`${Math.round(minP)} hPa`);set('seaWind',`${Math.round(maxW)} كم/س`);set('seaRain',`${maxR.toFixed(1)} ملم/ساعة`);set('seaCloud',`${Math.round(maxC)}%`);set('seaHumidity',`${Math.round(maxH)}%`);set('seaDirection',dir(a.direction));set('seaYemen',dist<900?'نشاط أقرب نسبيًا إلى اليمن':'لا توجد إشارة قريبة قوية حاليًا');set('seaImpact',dist<700&&a.score>20?'تحتاج متابعة التحديثات':'لا يظهر تأثير مباشر واضح على هدى حاليًا');set('seaWave','راجع خريطة Windy البحرية');set('seaWaveDirection','راجع خريطة Windy البحرية');if(s)s.textContent=(minP<=1004||maxW>=50||maxR>=10)?'⚠️ توجد مؤشرات نموذجية قوية نسبيًا في جزء من بحر العرب وتحتاج متابعة.':'✅ لا تظهر حاليًا إشارة نموذجية قوية لحالة مدارية قريبة من هدى.';window.seaLoaded=true;}catch(e){console.error(e);if(s)s.textContent='تعذر تحميل بيانات بحر العرب حاليًا. حاول مرة أخرى.';}};
window.openSea=function(){oldSea?.();window.loadSea();};
})();