(function(){"use strict";
var token=sessionStorage.getItem("rasid_owner_token")||"";
function q(id){return document.getElementById(id)}
function safe(v){return v==null?"—":String(v)}
function fmtDate(v){if(!v)return"—";try{return new Intl.DateTimeFormat("ar-YE",{dateStyle:"medium",timeStyle:"short",timeZone:"Asia/Aden"}).format(new Date(v))}catch(e){return safe(v)}}
async function api(path,opt){opt=opt||{};opt.headers=opt.headers||{};if(token)opt.headers.Authorization="Bearer "+token;if(opt.body)opt.headers["Content-Type"]="application/json";var r=await fetch(path,opt),d={};try{d=await r.json()}catch(e){}if(!r.ok)throw new Error(d.detail||"تعذر تنفيذ الطلب");return d}
function confidence(v){return({high:"عالية",medium:"متوسطة",low:"منخفضة",unknown:"غير كافية"})[v]||safe(v)}
function actionName(v){return({login:"تسجيل دخول",create_teacher:"إضافة معلّم",set_teacher_active:"تغيير حالة معلّم",submit_knowledge:"إرسال معلومة للمراجعة",review_knowledge:"مراجعة معلومة",set_ai_enabled:"تغيير حالة الذكاء الاصطناعي"})[v]||safe(v)}
async function load(){
 var tasks=[];
 tasks.push(api("/health").then(function(){q("health").innerHTML='<div class="statusline ok">● يعمل بصورة طبيعية</div><div class="small muted">الخادم وقاعدة البيانات متصلان.</div>'}).catch(function(){q("health").innerHTML='<span class="bad">تعذر فحص الحالة</span>'}));
 tasks.push(api("/ai/status").then(function(d){q("ai").innerHTML='<b>'+(d.enabled?'<span class="ok">مفعّل</span>':'<span class="warn">مغلق</span>')+'</b><br><span class="small">حد الزائر: '+safe(d.visitor_daily_limit)+' أسئلة يوميًا</span>'}));
 tasks.push(api("/weather/analysis/latest").then(function(d){var a=d.analysis||{};q("analysis").innerHTML='<b>الثقة: '+confidence(a.confidence)+'</b><br>'+safe(a.summary)+'<br><span class="small muted">آخر تحليل: '+fmtDate(a.created_at)+'</span>'}));
 tasks.push(api("/weather/models/latest").then(function(d){var pts=d.points||[],names=["ECMWF","AIFS","GFS","ICON","CMC"];q("models").innerHTML=names.map(function(n){var rows=pts.filter(function(x){return x.model===n}),last=rows[0];return '<div class="item"><b>'+n+'</b> — '+(rows.length?'<span class="ok">متوفر</span>':'<span class="bad">لا توجد نقاط</span>')+(last?'<br><span class="small muted">آخر تشغيل: '+fmtDate(last.run_time)+'</span>':'')+'</div>'}).join("")}));
 tasks.push(api("/weather/dust").then(function(d){var p=d.peak||{};q("dust").innerHTML='<b>لا يوجد تصنيف خطر آلي حاليًا</b><br><span class="small">أعلى تركيز غبار متوقع: '+safe(p.dust)+' µg/m³<br>'+fmtDate(p.time)+'</span>'}));
 tasks.push(api("/weather/arabian-sea").then(function(d){var n=(d.points||[]).length;q("sea").innerHTML='<b>المراقبة تعمل</b><br><span class="small">تم فحص '+n+' نقطة في بحر العرب.<br>الإشارات هنا مؤشرات موديلات وليست إعلان إعصار.</span>'}));
 tasks.push(loadTeachers());tasks.push(loadPending());tasks.push(loadApproved());tasks.push(loadAudit());
 await Promise.allSettled(tasks)
}
async function loadTeachers(){var d=await api("/admin/teachers"),a=d.teachers||[];q("teachers").innerHTML='<div><b>'+a.length+' من 5</b> معلّمين مسجلين</div>'+a.map(function(x){return '<div class="item"><b>'+safe(x.email)+'</b> — '+(x.active?'<span class="ok">نشط</span>':'<span class="warn">موقوف</span>')+'<button type="button" data-teacher="'+x.id+'" data-active="'+(!x.active)+'">'+(x.active?'إيقاف':'تفعيل')+'</button></div>'}).join("");q("teachers").querySelectorAll("[data-teacher]").forEach(function(b){b.onclick=function(){setTeacher(this.dataset.teacher,this.dataset.active==="true")}})}
async function loadPending(){var d=await api("/admin/knowledge/pending"),a=d.items||[];q("pending").innerHTML=a.length?a.map(function(x){return '<div class="item"><b>'+safe(x.subject)+'</b><br>'+safe(x.statement)+(x.source_note?'<br><span class="small muted">المصدر: '+safe(x.source_note)+'</span>':'')+'<br><span class="small">أرسلها: '+safe(x.submitted_by_email)+'</span><div class="actions"><button class="green" data-review="'+x.id+'" data-status="approved">اعتماد</button><button class="red" data-review="'+x.id+'" data-status="rejected">رفض</button></div></div>'}).join(""):'<span class="ok">لا توجد معلومات معلقة للمراجعة.</span>';q("pending").querySelectorAll("[data-review]").forEach(function(b){b.onclick=function(){review(this.dataset.review,this.dataset.status)}})}
async function loadApproved(){var d=await api("/knowledge"),a=d.items||[];q("approved").innerHTML=a.length?a.slice(0,50).map(function(x){return '<div class="item"><b>'+safe(x.subject)+'</b><br>'+safe(x.statement)+(x.source_note?'<br><span class="small muted">المصدر: '+safe(x.source_note)+'</span>':'')+'</div>'}).join(""):'لا توجد معرفة معتمدة حتى الآن.'}
async function loadAudit(){var d=await api("/admin/audit"),a=d.events||[];q("audit").innerHTML=a.slice(0,40).map(function(x){return '<div class="item"><b>'+actionName(x.action)+'</b> — '+safe(x.actor_email)+'<br><span class="small muted">'+fmtDate(x.created_at)+'</span></div>'}).join("")||"لا يوجد سجل بعد."}
async function panel(){try{var me=await api("/auth/me");if(me.role!=="owner")throw new Error("غير مصرح");q("login").classList.add("hide");q("panel").classList.remove("hide");await load()}catch(e){token="";sessionStorage.removeItem("rasid_owner_token")}}
q("go").onclick=async function(){q("msg").className="";q("msg").textContent="جارٍ تسجيل الدخول…";this.disabled=true;try{var d=await api("/auth/login",{method:"POST",body:JSON.stringify({email:q("email").value.trim(),password:q("pass").value})});token=d.access_token;sessionStorage.setItem("rasid_owner_token",token);q("msg").className="ok";q("msg").textContent="تم تسجيل الدخول";await panel()}catch(e){q("msg").className="bad";q("msg").textContent=e.message}finally{this.disabled=false}};
q("out").onclick=async function(){try{await api("/auth/logout",{method:"POST"})}catch(e){}sessionStorage.removeItem("rasid_owner_token");location.reload()};
async function setAI(enabled){if(!confirm(enabled?"هل تريد تشغيل الذكاء الاصطناعي؟":"هل تريد إيقاف الذكاء الاصطناعي؟"))return;try{await api("/admin/ai/settings",{method:"PATCH",body:JSON.stringify({enabled:enabled})});await load()}catch(e){alert(e.message)}}q("aiOn").onclick=function(){setAI(true)};q("aiOff").onclick=function(){setAI(false)};
q("refresh").onclick=async function(){if(!confirm("جلب تحديث جديد للموديلات الخمسة الآن؟"))return;this.disabled=true;try{await api("/admin/weather/refresh",{method:"POST"});alert("تم تحديث الموديلات");await load()}catch(e){alert(e.message)}finally{this.disabled=false}};
q("analyze").onclick=async function(){this.disabled=true;try{await api("/admin/weather/analyze",{method:"POST"});alert("تم تحديث التحليل");await load()}catch(e){alert(e.message)}finally{this.disabled=false}};
q("addTeacher").onclick=async function(){q("teacherMsg").textContent="";try{await api("/admin/teachers",{method:"POST",body:JSON.stringify({email:q("teacherEmail").value.trim(),password:q("teacherPass").value})});q("teacherEmail").value="";q("teacherPass").value="";q("teacherMsg").className="ok";q("teacherMsg").textContent="تمت إضافة المعلّم";await loadTeachers();await loadAudit()}catch(e){q("teacherMsg").className="bad";q("teacherMsg").textContent=e.message}};
async function setTeacher(id,active){if(!confirm(active?"تفعيل هذا المعلّم؟":"إيقاف هذا المعلّم؟"))return;try{await api("/admin/teachers/"+id+"/active",{method:"PATCH",body:JSON.stringify({active:active})});await loadTeachers();await loadAudit()}catch(e){alert(e.message)}}
q("submitKnowledge").onclick=async function(){try{await api("/knowledge/submissions",{method:"POST",body:JSON.stringify({subject:q("subject").value.trim(),statement:q("statement").value.trim(),source_note:q("source").value.trim()})});q("subject").value="";q("statement").value="";q("source").value="";q("knowledgeMsg").className="ok";q("knowledgeMsg").textContent="تم إرسال المعلومة للمراجعة";await loadPending();await loadAudit()}catch(e){q("knowledgeMsg").className="bad";q("knowledgeMsg").textContent=e.message}};
async function review(id,status){if(!confirm(status==="approved"?"اعتماد هذه المعلومة لتصبح من معرفة الراصد؟":"رفض هذه المعلومة؟"))return;try{await api("/admin/knowledge/"+id+"/review",{method:"PATCH",body:JSON.stringify({status:status})});await loadPending();await loadApproved();await loadAudit()}catch(e){alert(e.message)}}
q("ask").onclick=async function(){q("answer").innerHTML="جارٍ سؤال الراصد…";try{var d=await api("/ai/chat",{method:"POST",body:JSON.stringify({message:q("question").value.trim()})});q("answer").innerHTML='<div class="card">'+safe(d.answer||d.response||d.message)+'</div>'}catch(e){q("answer").innerHTML='<div class="warn">'+(e.message==="الذكاء الاصطناعي متوقف حاليًا"?"الذكاء الاصطناعي مغلق حاليًا. يمكنك تشغيله من بطاقة الذكاء الاصطناعي عندما تريد اختبار الراصد.":e.message)+'</div>'}};
if(token)panel();
})();